### ISSUE TITLE
Russian Localization

### ISSUE THREAD

**Issue by n116-software** [Nils277/FelineUtilityRovers#1]
This place is meant for the discussian of the russian localization of FUR.  
Feel free to discuss and add pull requensts as you like.

**Comment by n116-software** [comment]
@Tirathangil

**Comment by Tirathangil** [comment]
Hi again, I'm ready to work on localization. Sebra do not respond?

**Comment by n116-software** [comment]
He responded in the Forum and said that he is very busy at the moment. I think you can start with the translation and he joins later ;)

**Comment by Tirathangil** [comment]
ОК, I almost finished the translation. How can I see the translation of KSPedia in the game?

**Comment by n116-software** [comment]
For that i have to create new KSPedia entries where i added the russian texts manually. I just quickly did that and you can download the result from here; [felineutilityrovers_ru.ksp](https://www.dropbox.com/s/8fil58jl9c2rinq/felineutilityrovers_ru.ksp?dl=0)  
Just put the file into the *GameData/KerbetrotterLtd/FelineUtilityRover/KSPedia* folder and it should appear automatically in the game when you have set KSP to russian.

**Comment by Tirathangil** [comment]
Hi. Except that I translated several files, I also found a bug. Fuelcell module item takes the name from #LOC_FUR.canisterFuelCell.tags, not from #LOC_FUR.canisterFuelCell.title.

**Comment by n116-software** [comment]
Yep, found that one too. Will be fixed.
Thanks for the translation and the reported bug :)

Btw. i plan to add some additional parts to FUR in a future update. Would you be willing to translate them too once they are done?

**Comment by Tirathangil** [comment]
> Thanks for the translation and the reported bug :)

It's my pleasure. I am always ready to help. :)

> Would you be willing to translate them too once they are done?

Sure, no problem. These parts, accidentally,  jet engines for the fuselage? ;)

**Comment by n116-software** [comment]
Cool!
You mean something like this?
![](http://i.imgur.com/MCsRG9T.png)  
I guess the answer would be yes then ;)

**Comment by Tirathangil** [comment]
Yeah, it looks fantastic! Maybe, are the details planned in the form of side engines like as SG:A "Jumper"?  I somehow tried to make such an orbiting shuttle, it did not look very much. Non-native details looked bad. They worked the same way.

**Comment by n116-software** [comment]
Yep, i made post into the forums to let the users decide which thrusters to add.
[Forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/155344-130-feline-utility-rovers-v051-8-june-2017/&do=findComment&comment=3101758) 
The third one that can be seen in the above image was the clear favorite. The fourth one that can be attached to the sides also had some votes and will be added.  It might look a bit like the engines from SG:A ;)

**Comment by Tirathangil** [comment]
Maybe you'll consider the proposal for the concept of jet engines? I did not want to post this on the forum, because it's impolite. In addition, the model is made in 5 minutes - it looks awful ... Perhaps, it is possible to combine 3 and 4 variants as follows: 
![variant](https://user-images.githubusercontent.com/7392846/27550225-950d4104-5aa7-11e7-829a-29d7e06a1c07.png)

In my opinion, a separate mini-compartment for installing engines would look good in the paradigm of the rover system. In such systems from real life only nozzles are not placing: pumps, generators and other technical stuff mounting in a capsule or in a special compartment like this.
P.S. It's just my advice, nothing more.

**Comment by n116-software** [comment]
I'm not quite sure if i understand this part correctly. The part in the middle is the compartment and the thrusters can be attached to it at many positions? 
And should the compartment be attachabel in the surface of the parts or like the small canisters on the underbody?

P.S. i don't think it is impolite to post this in the forum. ;) 
Btw. should i link your profile from GitHub of from the forum to show who translated the mod?

**Comment by Tirathangil** [comment]
> Btw. should i link your profile from GitHub of from the forum to show who translated the mod?

It doesn't matter for me.  Maybe if in case of mistakes and inaccuracies in the translation, I could correct them if the forum users told me about them... 

> I'm not quite sure if i understand this part correctly. The part in the middle is the compartment and the thrusters can be attached to it at many positions?
And should the compartment be attachabel in the surface of the parts or like the small canisters on the underbody?

1. Yes. 2. Both options. :)
In general, this is a short compartment, long as a standard canister. The mount points look like the canister mount points for the other similar compartments, and in addition this compartment have mount points on the compartment hull.
Something like that, I think. :)

**Comment by n116-software** [comment]
I will see what i can do ;) Seems like an interesting idea. 

Btw, i just uploaded new texts to the russian files, that would need translation. https://github.com/Nils277/FelineUtilityRovers/commit/bfe9bba51bd49d2fac3366a25d2c3f691161cc1d
Would you be willing to translate them?

**Comment by Tirathangil** [comment]
> Would you be willing to translate them?

No problem, I will start to translation today.

> #LOC_FUR.ramp.rise = Rise Ramp

**Rise** or **raise**?

**Comment by n116-software** [comment]
you are right, it should be **raise**
