### ISSUE TITLE
Engines not filtered

### ISSUE THREAD

**Issue by Khalendros** [Nils277/FelineUtilityRovers#12]
I couldn't find any of the FUR engines in the editor except down in the Rovers tab, and on searching through, I think it's because they have

category = Engine

rather than

category = Propulsion

Happy to go through and form a PR if you'd like

ETA: On further looking, I'm actually wrong about the why. Squad's parts all use category = Engine, and NFT/WBI both (for example) use Propulsion, but they do show up.

**Comment by n116-software** [comment]
You are right, they are missing in the Engines Tab of the custom advanced filter of FUR. I will fix the plugin to add them there. 
If you mean the stock function filters, no parts are shown there by default. You can add them by setting:
*showInOneCategoryOnly = **false*** in the *GameData/KerbetrotterLtd/FelineUtilityRover/FelineUtilityRover.cfg*

**Comment by n116-software** [comment]
Should be fixed with #13

**Comment by Khalendros** [comment]
Forgive me for adding to this! I've got version 1.0.1, and they still aren't showing up in the regular engine tab or FUR's engine tab, though they're still in the Rovers tab, which may be added by another mod. I think it's because they naturally want to be in that tab with some label they have, so with the OneCategoryOnly flag set to true, that's where they show up. Gonna set it to false and see where else they appear, as I think for my personal play style, it'll work better for me to be able to find them in a few places. Thanks again!

Update: changed the flag, and now the engines are showing up in the stock function tab with the rest of the engines, but the engine category for the special FUR tab is still empty. I know where to find em, so I can make do just fine, and it's probably an interaction with another mod.

**Comment by n116-software** [comment]
Hmm, weird, Can you list what mods you have installed? They should be in the engine tab of FUR even then the OneCategoryOnly Flag is set to true.

**Comment by n116-software** [comment]
Well the engines missing in the FUR tab is my fault. I somehow managed to mess this up a second time and used an old code when compiling the plugin. Will be hopefully fixed with the next update.

**Comment by Khalendros** [comment]
KSP: 1.3 (Win64) - Unity: 5.4.0p4 - OS: Windows 10  (10.0.0) 64bit
000_AT_Utils - 1.4.4
Toolbar - 1.7.14
USI Tools - 0.9.3
Community Category Kit - 2.0.1
Community Resource Pack - 0.7.2
CommunityTechTree - 3.2
ConfigurableContainers - 2.4.1
CSIFreighter - 0.2.4
CryoEngines - 0.5.8
CryoTanks - 0.4.7
DMagic Orbital Science - 1.3.0.10
DynamicBatteryStorage - 1.1
Extraplanetary Launchpads - 5.8.2
Firespitter - 7.6
GroundConstruction - 1.2
HeatControl - 0.4
Interstellar Fuel Switch - 2.7.1
RasterPropMonitor - 0.29
Kerbal Attachment System - 0.6.3
KerbalAtomics - 0.4.8
Kerbal Engineer Redux - 1.1.3
Kerbal Foundries - 2.0.2.10
Feline Utility Rover - 1.0
Kerbal Inventory System - 1.7.6468.41490
KSP-AVC Plugin - 1.1.6.2
KSPWheel - 0.9.5.20
MarkIVSystem - 2.3.6
NearFutureConstruction - 0.8.3
NearFutureElectrical - 0.9.5
NearFutureLaunchVehicles - 1.1.1
NearFutureProps - 0.1
NearFuturePropulsion - 0.9.4
NearFutureSolar - 0.8.6
NearFutureSpacecraft - 0.7.3
Final Frontier - 1.3.2.3155
PatchManager - 0.0.9
Kerbal Planetary Base Systems - 1.5.2
RealPlume - Stock - 1.0
ReentryParticleEffect - 1.2.0.1
SCANsat - 1.1.8
ShipManifest - 5.2
StationPartsExpansion - 0.5.1
Stock Visual Enhancements - 1.2.5
Kerbal Alarm Clock - 3.8.5
Transfer Window Planner - 1.6.2
TweakScale - 2.3.6
USI Core - 0.4.2
USI Exploration Pack - 0.8.2
Freight Transport Tech - 0.7.2
Karbonite - 0.9.2
Konstruction - 0.2.2
MKS - 0.52.2
Universal Storage - 1.3.0.1
VesselViewerContinued - 0.8.5.1
WildBlueTools - 1.27
Kerbal Actuators - 1.0.6
Buffalo - 2.2.5
Deep Space Exploration Vessels - 2.3
Airships - 2.8.5
Kerbal KIS Items - 2.1.2
Mark One Laboratory Extensions - 1.8.8
Pathfinder - 1.11.5
OSE Workshop - 1.2.1
[x] Science! - 5.10

Here's my mod list if it still helps. Thanks!

**Comment by n116-software** [comment]
Should be finally fixed with #15
