### ISSUE TITLE
resourceFlowMode case issue in configs

### ISSUE THREAD

**Issue by Starwaster** [Nils277/FelineUtilityRovers#46]
ResourceFlowMode should be resourceFlowMode in  https://github.com/Nils277/FelineUtilityRovers/blob/master/For%20Release/GameData/KerbetrotterLtd/FelineUtilityRover/Patches/Realfuels.cfg

**Comment by n116-software** [comment]
Thanks will be fixed in the next release

**Comment by n116-software** [comment]
Fixed in 3180d2d
